version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: booking_postgres_dev
    environment:
      POSTGRES_DB: booking_system
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - booking_dev_network

  redis:
    image: redis:7-alpine
    container_name: booking_redis_dev
    ports:
      - "6379:6379"
    volumes:
      - redis_dev_data:/data
    networks:
      - booking_dev_network

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: booking_rabbitmq_dev
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_dev_data:/var/lib/rabbitmq
    networks:
      - booking_dev_network

volumes:
  postgres_dev_data:
  redis_dev_data:
  rabbitmq_dev_data:

networks:
  booking_dev_network:
    driver: bridge
